### ISSUE TITLE
Is this still developed

### ISSUE THREAD

**Issue by Leon0402** [greyltc/docker-archlinux#12]
According to the description, there will be a build on every sunday. But there hasn't been one for 3 month and the last one failed. 

Will there be any update?

**Comment by greyltc** [comment]
Just noticed! Working on a fix...

**Comment by greyltc** [comment]
Yeah, I'm still actively maintaining this. I've made a number of updates to the repo recently and it now rebuilds via GitHub Actions on a weekly basis. Images are now pushed to [Docker Hub](https://hub.docker.com/r/greyltc/archlinux) (as always) and now also [GitHub's package repository](https://github.com/greyltc/docker-archlinux/pkgs/container/archlinux).
