### ISSUE TITLE
Rebuild the Container because of Manual Intervention

### ISSUE THREAD

**Issue by Dav1dde** [greyltc/docker-archlinux#3]
Hey,

can you trigger a rebuild of the container, I am using this awesome container as a base image, unfortunately I cannot work with it right now because of: https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/

Could you trigger a rebuild of this base container to get rid of the issue?
Thanks!

**Comment by Dav1dde** [comment]
Thanks for the very fast update!

**Comment by greyltc** [comment]
no prob
