### ISSUE TITLE
Pacman: error while loading shared libraries

### ISSUE THREAD

**Issue by yogibare** [greyltc/docker-archlinux#5]
Good evening. 

First I would like to say thank you for all the hard work you put into this. I've learned a lot just by the style of your shell scripts. 

I've run into a problem while trying to run the build.sh step. 
I've posted the output of $docker build -t archlinux . at this pastebin
https://pastebin.com/FW0WJyrK

I am running;
Arch Linux
4.11.7-1-ARCH

Docker 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   89658bed64
 Built:        Fri May  5 22:40:58 2017
 OS/Arch:      linux/amd64
 Experimental: false

Also I made sure all of the required packages listed in the readme.md are installed. 

Please let me know what other information would help you help me with this problem. 

Thank you.

V/r

**Comment by greyltc** [comment]
Hey, thanks for the report. This should be fixed now!
